- name: Disable Default RP filtering on Node
  lineinfile: dest=/etc/sysctl.conf regexp="^#net.ipv4.conf.default.rp_filter" insertafter="#net.ipv4.conf.default.rp_filter" line="net.ipv4.conf.default.rp_filter=0" 
- name: Remove Default RP filtering comment 
  lineinfile: dest=/etc/sysctl.conf regexp="^#net.ipv4.conf.default.rp_filter" state=absent
- name: Disable all RP filtering on Node
  lineinfile: dest=/etc/sysctl.conf regexp="^#net.ipv4.conf.all.rp_filter" insertafter="#net.ipv4.all.default.rp_filter" line="net.ipv4.conf.all.rp_filter=0" 
- name: Remove RP filtering on comment
  lineinfile: dest=/etc/sysctl.conf regexp="^#net.ipv4.conf.default.rp_filter" state=absent

- name: Load new kernel parameters
  command: sysctl -p


