- name: Configure Neutron 
  template: src=etc/neutron/neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Configure Neutron ML2 plugin
  template: src=etc/neutron/plugins/ml2/ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini

- name: Restart OVS
  service: name=openvswitch-switch state=restarted

- name: Configure Nova to using Neutron
  template: src=etc/nova/nova-neutron.conf.j2 dest=/etc/nova/nova.conf

- name: Restart Nova-Compute
  service: name=nova-compute state=restarted

- name: Restart OVS agent
  service: name=neutron-plugin-openvswitch-agent state=restarted

