- name: Create OVS external bridge
    command: ovs-vsctl add-br br-ex

- name: Add interface to external bridge
    command: ovs-vsctl add-port br-ex eth2

- name: Restart OVS
    service: name=openvswitch-switch state=restarted
