- name: create neutron user in keystone
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: service 
    user: neutron 
    password: "{{ neutron_user_password }}"
  tags:
    - os-neutron

- name: add neutron user to the service tenant with the admin role
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: service 
    user: neutron 
    role: admin
  tags:
    - os-neutron

- name: add neutron endpoint
  keystone_service: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    region: "{{ openstack_region }}"
    name: neutron
    type: network
    description: Networking Service
    public_url: "{{ neutron_public_url }}"
    internal_url: "{{ neutron_internal_url }}"
    admin_url: "{{ neutron_admin_url }}"
  tags:
    - os-neutron
