- name: Configure glance-api
  template: src=etc/glance/glance-api.conf.j2 dest=/etc/glance/glance-api.conf

- name: Configure glance-registry
  template: src=etc/glance/glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf

- name: Perform a glance DB sync
  command: glance-manage db_sync

- name: Restart Image Services Registry
  service: name=glance-registry state=restarted

- name: Restart Image Services Registry
  service: name=glance-api state=restarted

- name: remove Glance SQLite DB
  file: path=/var/lib/glance/glance.sqlite state=absent
